#ifndef EVENTS_H
#define EVENTS_H

#define EV_READY 100
#define EV_ROUND_START 110
#define EV_STONE_PLACED 120
#define EV_SURRENDER 125
#define EV_WIN 130
#define EV_DRAW 140
#define EV_INVALID_MOVE 150
#define EV_PAUSED 160
#define EV_RESUMED 170
#define EV_RESTARTED 180
#define EV_BACK_TO_MENU 190
#define EV_EXIT_CONFIRM 200
#define EV_EXIT_CANCEL 210
#define EV_EXIT_APP 220
#define EV_ERROR 900

#define GS_MAIN_MENU 1000
#define GS_IN_GAME 1010
#define GS_PAUSED 1020
#define GS_CONFIRM_EXIT 1030

#define GAME_LOOP_BACK_TO_MENU 0
#define GAME_LOOP_EXIT_APP 1

#define PLAYER_ACTION_PAUSE 0
#define PLAYER_ACTION_PLACE 1
#define PLAYER_ACTION_SURRENDER 2

#define PLACE_OK 0
#define PLACE_ERR_INVALID_ARG 1
#define PLACE_ERR_GAME_OVER 2
#define PLACE_ERR_NOT_CURRENT_PLAYER 3
#define PLACE_ERR_OUT_OF_BOUNDS 4
#define PLACE_ERR_OCCUPIED 5
#define PLACE_ERR_INTERNAL 9

#endif
